Fix build for earlier GHC versions.
Earlier versions of GHC seem to require `TypeFamilies` in order to use
equational constraints:

```
library/ROC/ID/Serial/Internal.hs:34:14: error:
Error:     • Illegal equational constraint d ~ Digit
      (Use GADTs or TypeFamilies to permit this)
    • In the type signature:
        fromTuple :: d ~ Digit => (d, d, d, d, d, d, d) -> Serial
   |
34 | fromTuple :: d ~ Digit => (d, d, d, d, d, d, d) -> Serial
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

library/ROC/ID/Serial/Internal.hs:39:12: error:
Error:     • Illegal equational constraint d ~ Digit
      (Use GADTs or TypeFamilies to permit this)
    • In the type signature:
        toTuple :: d ~ Digit => Serial -> (d, d, d, d, d, d, d)
   |
39 | toTuple :: d ~ Digit => Serial -> (d, d, d, d, d, d, d)
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build roc-id-0.2.0.6 (which is required by
test:roc-id-test from roc-id-0.2.0.6).
```